Switch to gnu timeout

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -79,6 +79,22 @@ install:
     fi
     popd
   fi
+- | # Set up the timeout command
+  if which timeout >/dev/null
+  then
+    TIMEOUT=timeout
+  elif [ "$TRAVIS_OS_NAME" == "osx" ]
+  then
+    if ! which gtimeout >/dev/null
+    then
+      brew update
+      brew install coreutils
+    fi
+    TIMEOUT=gtimeout
+  else
+    echo "Unable to set up timeout command"
+    exit 1
+  fi
 - stack --no-terminal setup
 - stack --version
 - stack path
@@ -90,8 +106,10 @@ install:
     export CI_RELEASE=true
   fi
 script:
-# Set a timeout of 30 minutes.
-- travis_wait 30 ci/build.sh
+# Set a timeout of 30 minutes. We could also use travis_wait here, but
+# travis_wait doesn't produce any output until the command finishes, and also
+# doesn't always show all of the command's output.
+- $TIMEOUT 30m ci/build.sh
 before_deploy:
 - ./bundle/build.sh $OS_NAME
 deploy:
